"""initial schema with LiCo graph

Revision ID: 34ff97aaf8e1
Revises: 
Create Date: 2025-11-25 13:01:03.224790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34ff97aaf8e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name', 'entity_type', name='uq_entity_name_type')
    )
    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('themes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_table('triples',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_entity_id', sa.String(length=36), nullable=False),
    sa.Column('object_entity_id', sa.String(length=36), nullable=True),
    sa.Column('relation_type', sa.String(length=100), nullable=False),
    sa.Column('relation_text', sa.Text(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('is_state', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['object_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('session_summary_id', sa.String(length=36), nullable=False),
    sa.Column('start_message_id', sa.String(length=36), nullable=True),
    sa.Column('end_message_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('topic_hint', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['end_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['session_summary_id'], ['session_summaries.id'], ),
    sa.ForeignKeyConstraint(['start_message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('triple_session_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('triple_id', sa.String(length=36), nullable=False),
    sa.Column('session_summary_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['session_summary_id'], ['session_summaries.id'], ),
    sa.ForeignKeyConstraint(['triple_id'], ['triples.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('triple_id', 'session_summary_id', name='uq_triple_session')
    )
    op.create_table('triple_chunk_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('triple_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['memory_chunks.id'], ),
    sa.ForeignKeyConstraint(['triple_id'], ['triples.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('triple_id', 'chunk_id', name='uq_triple_chunk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triple_chunk_links')
    op.drop_table('triple_session_links')
    op.drop_table('memory_chunks')
    op.drop_table('triples')
    op.drop_table('session_summaries')
    op.drop_table('messages')
    op.drop_table('tags')
    op.drop_table('entities')
    op.drop_table('conversations')
    # ### end Alembic commands ###
